### PR TITLE
Updating runtime-version to 23.08 - Fixes #3

### LINKED ISSUE #3: Flatpak runtime is end of life
for full transparency, i already posted it on the main NBTExplorer repo but not sure if i am supposed to post it there or here
[the issue on main NBTExplorer repo](https://github.com/jaquadro/NBTExplorer/issues/142)

Flatpak shows warning that used runtime is EOL, please update to a newer runtime like 23.08

`Info: runtime org.freedesktop.Platform branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
   com.jaquadro.NBTExplorer
`

### PR DESCRIPTION
**Pull request by JordanL2**

### CODE REVIEW

**Comment by JordanL2** [comment]
bot, build com.jaquadro.NBTExplorer

**Comment by JordanL2** [comment]
bot, build com.jaquadro.NBTExplorer

**Comment by JordanL2** [comment]
Looks like flathub's buildbot is having issues today, will try again tomorrow.

**Comment by JordanL2** [comment]
bot, build com.jaquadro.NBTExplorer

**Comment by JordanL2** [comment]
bot, build com.jaquadro.NBTExplorer

**Comment by JordanL2** [comment]
Seems to be working fine as far as I can tell.

**Comment by ignapk** [comment]
Sorry for missing this and thank you for the PR :pray: It has been succeeded by https://github.com/flathub/com.jaquadro.NBTExplorer/pull/5, so closing.

**Pull request closed without merging**
